[package]
name = "simpledb-rust-impl"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde_json = "1.0.132"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json"] }
